services:
  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rails:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
